package com.tbh;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.tbh.dto.AuthRequest;
import com.tbh.dto.AuthResponse;
import com.tbh.entity.Payment;
import com.tbh.entity.RefreshToken;
import com.tbh.entity.Role;
import com.tbh.entity.User;
import com.tbh.repository.RefreshTokenRepository;
import com.tbh.repository.UserRepository;
import com.tbh.security.JwtTokenProvider;
import com.tbh.service.AuthService;
import com.tbh.service.RefreshTokenService;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.web.servlet.MockMvc;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.HexFormat;

import static org.junit.jupiter.api.Assertions.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

@SpringBootTest
@AutoConfigureMockMvc
@ActiveProfiles("test")
public class AuthSecurityTest {

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private ObjectMapper objectMapper;

    @Autowired
    private AuthService authService;

    @Autowired
    private UserRepository userRepository;

    @Autowired
    private RefreshTokenService refreshTokenService;

    @Autowired
    private RefreshTokenRepository refreshTokenRepository;

    @Autowired
    private PasswordEncoder passwordEncoder;

    @Autowired
    private JwtTokenProvider jwtTokenProvider;

    @Test
    @DisplayName("User password is encrypted via BCrypt and never stored in plain text")
    void testPasswordBCryptHashing() {
        String testEmail = "sec_" + System.currentTimeMillis() + "@tbhrentals.in";
        String testPhone = "98" + (long)(10000000 + Math.random() * 89999999);
        AuthRequest req = new AuthRequest();
        req.setEmail(testEmail);
        req.setPassword("SuperSecurePass123");
        req.setFullName("Security Tester");
        req.setPhoneNumber(testPhone);

        AuthResponse resp = authService.register(req);
        assertNotNull(resp.getToken());

        User user = userRepository.findByEmail(testEmail).orElseThrow();
        assertNotEquals("SuperSecurePass123", user.getPassword());
        assertTrue(passwordEncoder.matches("SuperSecurePass123", user.getPassword()));
    }

    @Test
    @DisplayName("Valid JWT token generated by provider can be authenticated and claims extracted")
    void testJwtTokenProvider() {
        String token = jwtTokenProvider.generateToken(999L, "jwt_pilot@tbhrentals.in", "ROLE_USER");
        assertTrue(jwtTokenProvider.validateToken(token));
        assertEquals("jwt_pilot@tbhrentals.in", jwtTokenProvider.getEmailFromToken(token));
        assertEquals("ROLE_USER", jwtTokenProvider.getRoleFromToken(token));
        assertEquals(999L, jwtTokenProvider.getUserIdFromToken(token));
    }

    @Test
    @DisplayName("OTP requests enforce 60s cooldown against spamming")
    void testOtpCooldown() {
        String phone = "9112233445";
        authService.sendOtp(phone);

        // Immediate repeated request without cooldown triggers exception
        assertThrows(IllegalArgumentException.class, () -> {
            authService.sendOtp(phone);
        });
    }

    @Test
    @DisplayName("Unauthenticated request to protected endpoint returns 401 JSON structure")
    void testUnauthenticatedEndpointReturns401Json() throws Exception {
        mockMvc.perform(get("/api/bookings/my/999"))
                .andExpect(status().isUnauthorized())
                .andExpect(content().contentType(MediaType.APPLICATION_JSON))
                .andExpect(jsonPath("$.status").value(401))
                .andExpect(jsonPath("$.error").value("Unauthorized"));
    }

    @Test
    @DisplayName("Regular user with ROLE_USER is forbidden (403) from admin endpoints")
    void testNonAdminForbiddenFromAdminEndpointReturns403Json() throws Exception {
        String userToken = jwtTokenProvider.generateToken(888L, "regular_rider@tbhrentals.in", "ROLE_USER");

        mockMvc.perform(get("/api/admin/bookings")
                        .header("Authorization", "Bearer " + userToken))
                .andExpect(status().isForbidden())
                .andExpect(content().contentType(MediaType.APPLICATION_JSON))
                .andExpect(jsonPath("$.status").value(403))
                .andExpect(jsonPath("$.error").value("Forbidden"));
    }

    @Test
    @DisplayName("Admin user with ROLE_ADMIN can access admin endpoints")
    void testAdminCanAccessAdminEndpoint() throws Exception {
        String adminToken = jwtTokenProvider.generateToken(1L, "admin_user@tbhrentals.in", "ROLE_ADMIN");

        mockMvc.perform(get("/api/admin/bookings")
                        .header("Authorization", "Bearer " + adminToken))
                .andExpect(status().isOk());
    }

    @Test
    @DisplayName("User cannot query another user's KYC status (anti-tampering IDOR defense)")
    void testCrossUserKycAccessForbidden() throws Exception {
        String testEmail = "kyc_owner_" + System.currentTimeMillis() + "@tbhrentals.in";
        User user = new User("KYC Owner", testEmail, "99" + (long)(10000000 + Math.random() * 89999999), "pass123", Role.ROLE_USER);
        user = userRepository.save(user);

        String userToken = jwtTokenProvider.generateToken(user.getId(), user.getEmail(), "ROLE_USER");

        // Attempting to query KYC of someone else (e.g. ID 99999L) must be rejected with 403 Forbidden
        mockMvc.perform(get("/api/kyc/status")
                        .param("userId", "99999")
                        .header("Authorization", "Bearer " + userToken))
                .andExpect(status().isForbidden());
    }

    @Test
    @DisplayName("Public catalog endpoints (vehicles, cities) are accessible without authentication")
    void testPublicCatalogAccessibleWithoutAuth() throws Exception {
        mockMvc.perform(get("/api/vehicles"))
                .andExpect(status().isOk());
        mockMvc.perform(get("/api/locations/cities"))
                .andExpect(status().isOk());
    }

    @Test
    @DisplayName("Refresh tokens are SHA-256 hashed in database and never stored in raw text")
    void testRefreshTokenHashedInDatabase() throws Exception {
        String testEmail = "refresh_sec_" + System.currentTimeMillis() + "@tbhrentals.in";
        User user = new User("Refresh User", testEmail, "97" + (long)(10000000 + Math.random() * 89999999), "pass123", Role.ROLE_USER);
        user = userRepository.save(user);

        RefreshToken tokenObj = refreshTokenService.createRefreshToken(user);
        String rawToken = tokenObj.getRawToken();
        assertNotNull(rawToken, "Client must receive raw token");

        MessageDigest digest = MessageDigest.getInstance("SHA-256");
        String expectedHash = HexFormat.of().formatHex(digest.digest(rawToken.getBytes(StandardCharsets.UTF_8)));

        // Verify that the stored entity in DB contains the 64-character SHA-256 hash, not the raw token
        RefreshToken dbToken = refreshTokenRepository.findByToken(expectedHash).orElse(null);
        assertNotNull(dbToken, "Database must store the SHA-256 hash");
        assertEquals(expectedHash, dbToken.getToken());
        assertNotEquals(rawToken, dbToken.getToken());
        assertEquals(64, dbToken.getToken().length());

        // Looking up raw token directly in database should return nothing
        assertFalse(refreshTokenRepository.findByToken(rawToken).isPresent());
    }

    @Test
    @DisplayName("User password field is protected and never serialized in JSON responses")
    void testUserEntityPasswordNotSerializedInJson() throws Exception {
        User user = new User("Secret User", "secret@tbh.in", "9999999999", "super_secret_password", Role.ROLE_USER);
        user.setId(777L);

        String json = objectMapper.writeValueAsString(user);

        assertFalse(json.contains("super_secret_password"), "Password must not be in serialized JSON");
        assertFalse(json.contains("\"password\""), "Password key must not be in serialized JSON");
    }

    @Test
    @DisplayName("Payment razorpaySignature is protected with @JsonIgnore and not serialized")
    void testPaymentEntitySignatureNotSerializedInJson() throws Exception {
        Payment payment = new Payment();
        payment.setRazorpayOrderId("order_123");
        payment.setRazorpayPaymentId("pay_123");
        payment.setRazorpaySignature("secret_razorpay_sig_12345");

        String json = objectMapper.writeValueAsString(payment);

        assertFalse(json.contains("secret_razorpay_sig_12345"), "Signature must not be serialized");
        assertFalse(json.contains("razorpaySignature"), "Signature field must be @JsonIgnore");
    }

    @Test
    @DisplayName("User registration always assigns ROLE_USER, preventing privilege escalation")
    void testRegistrationCannotEscalatePrivilege() {
        String testEmail = "escalate_" + System.currentTimeMillis() + "@tbhrentals.in";
        AuthRequest req = new AuthRequest();
        req.setEmail(testEmail);
        req.setPassword("SecurePassword123");
        req.setFullName("Privilege Attacker");

        AuthResponse resp = authService.register(req);
        assertEquals("ROLE_USER", resp.getRole());

        User user = userRepository.findByEmail(testEmail).orElseThrow();
        assertEquals(Role.ROLE_USER, user.getRole());
    }
}
